development:
  clients:
    default:
      database: communique_development
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: communique_test
      hosts:
        - localhost:27017
